openapi: 3.0.1
info:
  title: セキュリティチェックAPI
  description: セキュリティチェック機能のAPI定義
  version: 1.0.0
tags:
  - name: セキュリティチェック
    description: セキュリティチェック関連のAPI
paths:
  /security-checks:
    get:
      summary: セキュリティチェック記録一覧の取得
      deprecated: false
      description: すべてのセキュリティチェック記録を取得し、デバイスIDおよびユーザーIDでの絞り込みとページング取得に対応します
      tags:
        - セキュリティチェック
      parameters:
      - name: page
        in: query
        description: ページ番号
        required: true
        example: 1
        schema:
          type: integer
          default: 1
      - name: size
        in: query
        description: 1ページ当たりの件数
        required: false
        example: 10
        schema:
          type: integer
          default: 10
      - name: deviceId
        in: query
        description: デバイスID
        required: false
        example: デバイス001
        schema:
          type: string
      - name: userId
        in: query
        description: ユーザーID
        required: false
        example: ユーザー001
        schema:
          type: string
      responses:
        '200':
          description: 一覧取得成功
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/SampleCheckDTO'
                  required:
                  - data
              example:
                code: 200
                message: 取得に成功しました
                data:
                - samplingId: record001
                  userId: EMP00123
                  deviceId: DEV2024001
                  name: 山田太郎
                  reportId: SEC20240115001
                  updateDate: '2024-01-15'
                  createTime: '2024-01-10 09:00:00'
                  updateTime: '2024-01-15 10:00:00'
                  installedSoftware: true
                  disposalMeasures: 許可されていないソフトウェアをアンインストールし、システムを再起動しました
                  screenSaverPwd: true
                  usbInterface: false
                  securityPatch: true
                  antivirusProtection: true
                  bootAuthentication: true
                - samplingId: record002
                  userId: EMP00456
                  deviceId: DEV2024002
                  name: 佐藤花子
                  reportId: SEC20240115002
                  updateDate: '2024-01-16'
                  createTime: '2024-01-11 09:00:00'
                  updateTime: '2024-01-16 11:00:00'
                  installedSoftware: false
                  disposalMeasures: なし
                  screenSaverPwd: true
                  usbInterface: true
                  securityPatch: true
                  antivirusProtection: true
                  bootAuthentication: true
                total: 120
                page: 1
                size: 10
      security: []
    post:
      summary: 新規作成
      deprecated: false
      description: セキュリティチェック項目を新規作成します
      tags:
        - セキュリティチェック
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleCheckDTO'
            example:
              samplingId: record001
              userId: EMP00123
              deviceId: DEV2024001
              name: 山田太郎
              reportId: SEC20240115001
              updateDate: '2024-01-15'
              createTime: '2024-01-10 09:00:00'
              updateTime: '2024-01-15 10:00:00'
              installedSoftware: true
              disposalMeasures: 許可されていないソフトウェアをアンインストールし、システムを再起動しました
              screenSaverPwd: true
              usbInterface: false
              securityPatch: true
              antivirusProtection: true
              bootAuthentication: true
        required: true
      responses:
        '200':
          description: 追加に成功しました
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/SampleCheckDTO'
                  required:
                  - data
              example:
                code: 200
                message: 追加に成功しました
                data:
                  samplingId: record001
                  userId: EMP00123
                  deviceId: DEV2024001
                  name: 山田太郎
                  reportId: SEC20240115001
                  updateDate: '2024-01-15'
                  createTime: '2024-01-10 09:00:00'
                  updateTime: '2024-01-15 10:00:00'
                  installedSoftware: true
                  disposalMeasures: 許可されていないソフトウェアをアンインストールし、システムを再起動しました
                  screenSaverPwd: true
                  usbInterface: false
                  securityPatch: true
                  antivirusProtection: true
                  bootAuthentication: true
      security: []
  /security-checks/export:
    get:
      summary: レポート出力
      deprecated: false
      description: ''
      tags:
        - セキュリティチェック
      parameters:
      - name: reportCode
        in: query
        description: レポート番号（レポート番号で絞り込み）
        required: true
        example: ISMSFM1601-1
        schema:
          type: string
      responses:
        '200':
          description: レポートファイルを返却します。ファイル名はサーバ側で動的に生成されます
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /security-checks/{samplingId}:
    get:
      summary: セキュリティチェック詳細情報の取得
      deprecated: false
      description: セキュリティチェック記録の詳細情報を取得します
      operationId: query-checks-by-id
      tags:
        - セキュリティチェック
      parameters:
      - name: samplingId
        in: path
        description: セキュリティチェック記録ID
        example: record001
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 詳細取得成功
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/SampleCheckDTO'
                  required:
                  - data
              example:
                code: 200
                message: 取得に成功しました
                data:
                  samplingId: record001
                  userId: EMP00123
                  deviceId: DEV2024001
                  name: 山田太郎
                  reportId: SEC20240115001
                  updateDate: '2024-01-15'
                  createTime: '2024-01-10 09:00:00'
                  updateTime: '2024-01-15 10:00:00'
                  installedSoftware: true
                  disposalMeasures: 許可されていないソフトウェアをアンインストールし、システムを再起動しました
                  screenSaverPwd: true
                  usbInterface: false
                  securityPatch: true
                  antivirusProtection: true
                  bootAuthentication: true
        '404':
          description: 対象が存在しません
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
              example:
                code: 404
                message: 対応するセキュリティチェック記録が見つかりません
                data: {}
      security: []
    put:
      summary: 更新
      deprecated: false
      description: セキュリティチェック記録を更新します
      tags:
        - セキュリティチェック
      parameters:
      - name: samplingId
        in: path
        description: セキュリティチェック記録ID
        required: true
        example: record001
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleCheckDTO'
            example:
              samplingId: record001
              userId: EMP00123
              deviceId: DEV2024001
              name: 山田太郎
              reportId: SEC20240115001
              updateDate: '2024-02-01'
              createTime: '2024-01-10 09:00:00'
              updateTime: '2024-02-01 18:00:00'
              installedSoftware: false
              disposalMeasures: アンインストール済み、再起動済み
              screenSaverPwd: true
              usbInterface: true
              securityPatch: true
              antivirusProtection: true
              bootAuthentication: true
              creater: システム管理者
              updater: 山田太郎
        required: true
      responses:
        '200':
          description: 更新に成功しました
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      $ref: '#/components/schemas/SampleCheckDTO'
                  required:
                  - data
              example:
                code: 200
                message: 更新に成功しました
                data:
                  samplingId: record001
                  userId: EMP00123
                  deviceId: DEV2024001
                  name: 山田太郎
                  reportId: SEC20240115001
                  updateDate: '2024-02-01'
                  createTime: '2024-01-10 09:00:00'
                  updateTime: '2024-02-01 18:00:00'
                  installedSoftware: false
                  disposalMeasures: アンインストール済み、再起動済み
                  screenSaverPwd: true
                  usbInterface: true
                  securityPatch: true
                  antivirusProtection: true
                  bootAuthentication: true
                  creater: システム管理者
                  updater: 山田太郎
      security: []
    delete:
      summary: 削除
      deprecated: false
      description: セキュリティチェック記録を1件削除します
      tags:
        - セキュリティチェック
      parameters:
      - name: samplingId
        in: path
        description: セキュリティチェック記録ID
        required: true
        example: record001
        schema:
          type: string
      responses:
        '200':
          description: 削除に成功しました
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/ApiResponse'
                - type: object
                  properties:
                    data:
                      type: object
                  required:
                  - data
              example:
                code: 200
                message: 削除に成功しました
                data: {}
      security: []
components:
  schemas:
    SampleCheckDTO:
      title: SampleCheckDTO
      type: object
      required:
      - samplingId
      - userId
      - deviceId
      - name
      - reportId
      - updateDate
      properties:
        samplingId:
          type: string
          maxLength: 50
        userId:
          type: string
          maxLength: 50
        deviceId:
          type: string
          maxLength: 50
        installedSoftware:
          type: boolean
          nullable: true
        disposalMeasures:
          type: string
          maxLength: 65535
          nullable: true
        name:
          type: string
          maxLength: 100
        reportId:
          type: string
          maxLength: 50
        updateDate:
          type: string
          format: date
        screenSaverPwd:
          type: boolean
          nullable: true
        usbInterface:
          type: boolean
          nullable: true
        securityPatch:
          type: boolean
          nullable: true
        antivirusProtection:
          type: boolean
          nullable: true
        bootAuthentication:
          type: boolean
          nullable: true
        createTime:
          type: string
          description: 未指定时由システムで現在時刻が設定されます
        creater:
          type: string
          maxLength: 100
          nullable: true
        updateTime:
          type: string
          description: 未指定時由システムで現在時刻が設定されます
        updater:
          type: string
          maxLength: 100
          nullable: true
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          description: ステータスコード
        message:
          type: string
          description: メッセージ
        data:
          description: 業務データ
        total:
          type: integer
          format: int64
          nullable: true
        page:
          type: integer
          nullable: true
        size:
          type: integer
          nullable: true
      required:
      - code
      - message
      example:
        code: 200
        message: 取得に成功しました
        data:
          samplingId: record001
          userId: EMP00123
          deviceId: DEV2024001
          name: 山田太郎
          reportId: SEC20240115001
          updateDate: '2024-01-15'
          createTime: '2024-01-10 09:00:00'
          updateTime: '2024-01-15 10:00:00'
          installedSoftware: true
          disposalMeasures: 許可されていないソフトウェアをアンインストールし、システムを再起動しました
          screenSaverPwd: true
          usbInterface: false
          securityPatch: true
          antivirusProtection: true
          bootAuthentication: true
          updater: 山田太郎
          creater: システム管理者
        total: 120
        page: 1
        size: 10
  responses: {}
  securitySchemes: {}
servers:
- url: http://localhost:8080/api
  description: 開発環境
security: []
