openapi: 3.0.0
info:
  title: 設備API
  description: 設備の追加・削除・更新・参照およびエクスポート機能のAPI定義
  version: 1.0.0
servers:
  - url: /api
    description: デフォルトAPIサーバーアドレス
tags:
  - name: devices
    description: 設備管理モジュール

paths:
# 設備モジュールインターフェース定義
  /devices:
    get:
      tags:
        - devices
      summary: 設備リスト照会
      description: ページング・フィルタリングに対応した設備リスト照会インターフェース
      parameters:
        - name: page
          in: query
          description: ページ番号
          required: false
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          description: 1ページあたりの件数
          required: false
          schema:
            type: integer
            example: 15
        - name: userId
          in: query
          description: ユーザーID（フィルタ条件）
          required: false
          schema:
            type: string
            example: JS0014
      responses:
        '200':
          description: 機器リストの取得に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Device'
                  total:
                    type: integer
                    description: 総件数
                    example: 100
                  page:
                    type: integer
                    example: 1
                  size:
                    type: integer
                    example: 10
        #パラメーター検証例外の処理時は、400 を返却します
        #認証失敗例外の処理時は、401 を返却します
        #リソースが見つからない例外の処理時は、404 を返却します
        #その他のすべての例外の処理時は、500 を返却します
        '400':
          description: パラメータ検証エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                      type: integer
                      example: 400
                  error:
                    type: string
                    example: "パラメータ検証エラー"
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                      type: integer
                      example: 401
                  error:
                    type: string
                    example: "認証失敗"
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 500
                  error:
                    type: string
                    example: "サーバー内部エラー"


    post:
          tags:
            - devices
          summary: 設備を新規追加
          description: 新しい設備情報を追加します
          operationId: insertDevice
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Device'
                  
          responses:
            "200":
              description: データの挿入に成功しました
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                        code:
                          type: integer
                          example: 200
                    
                        data:
                          type: array
                          items:
                            $ref: '#/components/schemas/Device'
            "400":
              description: パラメータ検証に失敗しました  
              content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        code: 
                              type: integer
                              example: 400
                        error:                      
                          type: string
                          example: "パラメータ検証に失敗しました" 
            "500":
              description: サーバーエラー
              content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        code: 
                          type: integer
                          example: 500
                        error:
                          type: string
                          example: "サーバーエラー"


  /devices/{id}:
    parameters:
      - name: id
        in: path
        description: 設備ID
        required: true
        schema:
          type: string
          example: HYRON-221129 PC-DC-089
    get:
      tags:
        - devices
      summary: 設備詳細照会
      description: 設備IDに基づき設備詳細情報を照会
      responses:
        '200':
          description: 設備詳細情報の取得に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      deviceInfo:
                        $ref: '#/components/schemas/Device'
                      ipInfoList:
                        type: array
                        items:
                          $ref: '#/components/schemas/deviceIp'
                      monitorInfoList:
                        type: array
                        items:
                          $ref: '#/components/schemas/monitorInfo'
        '400':
          description: パラメータ検証エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 400
                  error:
                    type: string
                    example: "パラメータ検証エラー"
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 401
                  error:
                    type: string
                    example: "認証失敗"
        '404':
          description: リソースが見つかりません
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "リソースが見つかりません"
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 500
                  error:
                    type: string
                    example: "サーバー内部エラー"
    put:
      tags:
        - devices
      summary: 設備情報を編集
      description: 設備情報を修正します
      operationId: updateDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
              
      responses:
        "200":
          description: データの編集に成功しました
          content:
            application/json:
              schema:
                type: object
                properties:
                    code:
                      type: integer
                      example: 200
                
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/Device'
        "400":
          description: パラメータ検証に失敗しました  
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                          type: integer
                          example: 400
                    error:
                      type: string
                      example: "パラメータ検証に失敗しました"


        "404":
          description: リソースが存在しません
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                          type: integer
                          example: 404
                    error:
                      type: string
                      example: "設備が存在しません"
        "500":
          description: サーバーエラー
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                          type: integer
                          example: 500
                    error:
                      type: string
                      example: "サーバーエラー"   
    
    
    delete:
      tags:
        - devices
      summary: デバイスを削除
      description: デバイスIDに基づいて指定されたデバイスの記録を削除する
      operationId: deleteDevice
      responses:
        "200":
          description: デバイスの削除に成功しました。返却内容はありません。
        "404":
          description: デバイスが存在しません
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                      type: integer
                      example: 404
                  error:
                    type: string
                    example: "デバイスが存在しません"
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 500
                  error:
                    type: string
                    example: "サーバー内部エラー"
  /devices/export:
    get:
      tags:
        - devices
      summary: デバイス情報をエクスポート
      description: すべてのデバイス情報をExcelファイルにエクスポートする
      operationId: exportDevices
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: query
          required: false
          schema:
            type: string
            description: フィルター条件：ユーザー社員番号
            example: "USR001"
      responses:
        "200":
          description: デバイスリストのエクスポートに成功しました
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "サーバー内部エラー"
components:
  schemas:
  # 機器エンティティ
    Device:
      type: object
      description: 機器オブジェクト
      properties:
        deviceId:        
          type: string
          description: 機器番号（プライマリキー）
          example: HYRON-221129 PC-DC-089
        deviceModel:
          type: string
          description: ホストモデル
          example: dell-5000
        computerName:
          type: string
          description: コンピュータ名
          example: DA04-LINF-PC
        LoginUserName:
          type: string
          description: ログインユーザ名
          example: linf-nrtu
        project:
          type: string
          description: 所属プロジェクト
          example: DA05支援
        devRoom:
          type: string
          description: 所属開発室
          example: M10
        jobNumber:
          type: string
          description: 従業員番号（所属ユーザ、外部キー）
          example: JS0014
        remark:
          type: string
          description: 備考
          example: D1005開発室
        selfConfirmId:
          type: integer
          description: 本人確認ID（辞書項目：CONFIRM_STATUS 関連、外部キー）
          example: 1
        osId:
          type: integer
          description: OSID（辞書項目：OS_TYPE 関連、外部キー）
          example: 3
        memoryId:
          type: integer
          description: メモリID（辞書項目：MEMORY_SIZE 関連、外部キー）
          example: 1
        ssdId:
          type: integer
          description: SSDID（辞書項目：SSD_SIZE 関連、外部キー）
          example: 1
        hddId:
          type: integer
          description: HDDID（辞書項目：HDD_SIZE 関連、外部キー）
          example: 2
        createTime:
          type: string
          format: date-time
          description: 作成日時
          example: 2026-01-02T09:00:00+08:00
        creater:
          type: string
          description: 作成者
          example: JS0014
        updateTime:
          type: string
          format: date-time
          description: 更新日時
          example: 2026-01-02T10:00:00+08:00
        updater:
          type: string
          description: 更新者
          example: JS0014

  # 機器IP情報エンティティ
    deviceIp:
      type: object
      description: 機器のIP情報
      properties:
        ipId:
          type: integer
          description: IP番号（プライマリキー）
          example: 1
        deviceId:
          type: string
          description: 機器番号（外部キー）
          example: HYRON-221129 PC-DC-089
        ipAddress:
          type: string
          description: IPアドレス（ユニーク）
          example: 173.28.100.112
        createTime:
          type: string
          format: date-time
          description: 作成日時
          example: 2026-01-02T09:00:00+08:00
        creater:
          type: string
          description: 作成者
          example: JS0014
        updateTime:
          type: string
          format: date-time
          description: 更新日時
          example: 2026-01-02T10:00:00+08:00
        updater:
          type: string
          description: 更新者
          example: JS0014

  # 機器モニター情報エンティティ
    monitorInfo:
      type: object
      description: モニター情報
      properties:
        monitorId:
          type: integer
          description: モニター番号（プライマリキー）
          example: 1
        deviceId:
          type: string
          description: 機器番号（外部キー）
          example: HYRON-221129 PC-DC-089
        monitorName:
          type: string
          description: モニター名
          example: HYRON-241118 Minitor-131
        createTime:
          type: string
          format: date-time
          description: 作成日時
          example: 2026-01-02T09:00:00+08:00
        creater:
          type: string
          description: 作成者
          example: JS0014
        updateTime:
          type: string
          format: date-time
          description: 更新日時
          example: 2026-01-02T10:00:00+08:00
        updater:
          type: string
          description: 更新者
          example: JS0014

  # ページング応答
    PaginatedResponse:
      type: object
      properties:
        code:
          type: integer
          description: ステータスコード
        data:
          type: array
          items:
            type: object
          description: データリスト
        total:
          type: integer
          description: 総件数
        page:
          type: integer
          description: 現在のページ
        size:
          type: integer
          description: ページサイズ
        totalPages:
          type: integer
          description: 総ページ数

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWTトークンを使用した認証