openapi: 3.0.3
info:
  title: 認証 API - パスワード変更
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /auth/change-password:
    post:
      summary: パスワード変更
      description: ログイン済みのユーザーが userId を使用して自身のログインパスワードを変更します。有効な JWT が必要です。
      tags:
        - Auth
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: パスワードの更新が成功しました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangePasswordResponse'
        '400':
          description: ビジネスロジックの検証に失敗しました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                wrongCurrent:
                  value: { code: 40001, msg: 現在のパスワードが正しくありません }
                weakNew:
                  value: { code: 40002, msg: 新しいパスワードが強度要件を満たしていません }
                sameAsOld:
                  value: { code: 40003, msg: 新しいパスワードは古いパスワードと同じにすることはできません }
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChangePasswordRequest:
      type: object
      required:
        - userId
        - currentPassword
        - newPassword
      properties:
        userId:
          type: string
          description: ユーザー主キー（user_id）
          example: admin001
        currentPassword:
          type: string
          format: password
          description: 現在のパスワード
          example: T+vWQMZO0qaTX+mfzbgrYA==
        newPassword:
          type: string
          format: password
          minLength: 8
          pattern: '^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
          description: 新しいパスワードは、文字、数字、特殊文字を含む必要があります
          example: Y7bZjOtwGJorGjrKfLV2yQ==

    ChangePasswordResponse:
      type: object
      properties:
        code:
          type: integer
          example: 0
        msg:
          type: string
          example: パスワードが更新されました。再度ログインしてください。

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: ビジネスエラーコード
        msg:
          type: string
          description: エラーメッセージ

  responses:
    Unauthorized:
      description: JWT が無効または期限切れです
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example: { code: 40100, msg: トークンが無効または期限切れです }
    InternalError:
      description: サーバー内部エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example: { code: 50000, msg: サーバーが混雑しています。しばらくしてから再度お試しください }