openapi: 3.0.0
info:
  title: 設備管理システム API
  description: 部門内設備管理システムのAPIドキュメント、設備管理、権限管理、検査表管理などの機能を含む
  version: 1.0.0
  contact:
    name: システム管理者
    email: admin@company.com

servers:
  - url: http://localhost:8080/api
    description: ローカル開発環境
  - url: https://api.equipment.company.com/api
    description: 本番環境



paths:

  # 設備管理
  /devices: 
    post:
      tags:
        - devices
      summary: 設備を新規追加
      description: 新しい設備情報を追加します
      operationId: insertDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
              
      responses:
        "200":
          description: データの挿入に成功しました
          content:
            application/json:
              schema:
                type: object
                properties:
                    code:
                      type: integer
                      example: 200
                
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/Device'
        "400":
          description: パラメータ検証に失敗しました  
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                          type: integer
                          example: 400
                    error:                      
                      type: string
                      example: "パラメータ検証に失敗しました" 
        "500":
          description: サーバーエラー
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                      type: integer
                      example: 500
                    error:
                      type: string
                      example: "サーバーエラー"


  /devices/{deviceId}:
    parameters:
      - name: id
        in: path
        description: 設備ID
        required: true
        schema:
          type: string
          example: HYRON-221129 PC-DC-089
    put:
      tags:
        - devices
      summary: 設備情報を編集
      description: 設備情報を修正します
      operationId: updateDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
              
      responses:
        "200":
          description: データの編集に成功しました
          content:
            application/json:
              schema:
                type: object
                properties:
                    code:
                      type: integer
                      example: 200
                
                    data:
                      type: array
                      items:
                        $ref: '#/components/schemas/Device'
        "400":
          description: パラメータ検証に失敗しました  
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                          type: integer
                          example: 400
                    error:
                      type: string
                      example: "パラメータ検証に失敗しました"


        "404":
          description: リソースが存在しません
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                          type: integer
                          example: 404
                    error:
                      type: string
                      example: "設備が存在しません"
        "500":
          description: サーバーエラー
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    code: 
                          type: integer
                          example: 500
                    error:
                      type: string
                      example: "サーバーエラー"
  

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # 设备相关模型


    Device:
          type: object
          description: 機器オブジェクト
          properties:
            deviceId:
              type: string
              description: 機器番号（プライマリキー）
              example: HYRON-221129 PC-DC-089
            deviceModel:
              type: string
              description: ホストモデル
              example: dell-5000
            computerName:
              type: string
              description: コンピュータ名
              example: DA04-LINF-PC
            LoginUserName:
              type: string
              description: ログインユーザ名
              example: linf-nrtu
            project:
              type: string
              description: 所属プロジェクト
              example: DA05支援
            devRoom:
              type: string
              description: 所属開発室
              example: M10
            jobNumber:
              type: string
              description: 従業員番号（所属ユーザ、外部キー）
              example: JS0014
            remark:
              type: string
              description: 備考
              example: D1005開発室
            selfConfirmId:
              type: integer
              description: 本人確認ID（辞書項目：CONFIRM_STATUS 関連、外部キー）
              example: 1
            osId:
              type: integer
              description: OSID（辞書項目：OS_TYPE 関連、外部キー）
              example: 3
            memoryId:
              type: integer
              description: メモリID（辞書項目：MEMORY_SIZE 関連、外部キー）
              example: 1
            ssdId:
              type: integer
              description: SSDID（辞書項目：SSD_SIZE 関連、外部キー）
              example: 1
            hddId:
              type: integer
              description: HDDID（辞書項目：HDD_SIZE 関連、外部キー）
              example: 2
            createTime:
              type: string
              format: date-time
              description: 作成日時
              example: 2026-01-02T09:00:00+08:00
            creater:
              type: string
              description: 作成者
              example: JS0014
            updateTime:
              type: string
              format: date-time
              description: 更新日時
              example: 2026-01-02T10:00:00+08:00
            updater:
              type: string
              description: 更新者
              example: JS0014

    DeviceIP:
      type: object
      properties:
        ip_id:
          type: string
          description: IP番号(主キー)
        device_id:
          type: string
          description: 機器番号(外部キー)
        ip_address:
          type: string
          description: IPアドレス(ユニーク)
        create_time:
          type: string
          format: date-time
          description: 作成時間
        update_time:
          type: string
          format: date-time
          description: 更新時間
        updater:
          type: string
          description: 更新者
        is_deleted:
          type: integer
          format: int16
          description: 論理削除フラグ(0=未削除、1=削除済)
      required:
        - ip_id
        - device_id

    DevicePermission:
      type: object
      properties:
        permission_id:
          type: string
          description: 権限番号(主キー)
        job_number:
          type: string
          description: 社員番号(外部キー)
        domain_status_id:
          type: integer
          format: int64
          description: ドメインステータスID(ディクショナリ項目に関連：DOMAIN_STATUS)
        domain_group:
          type: string
          description: ドメイン内グループ名
        no_domain_reason:
          type: string
          description: ドメイン未加入理由
        smartit_status_id:
          type: integer
          format: int64
          description: SmartITステータスID(ディクショナリ項目に関連：SMARTIT_STATUS)
        no_smartit_reason:
          type: string
          description: SmartIT未インストール理由
        usb_status_id:
          type: integer
          format: int64
          description: USBステータスID(ディクショナリ項目に関連：USB_STATUS)
        usb_reason:
          type: string
          description: USB使用許可理由
        usb_expire_date:
          type: string
          format: date
          description: USB使用有効期限
        antivirus_status_id:
          type: integer
          format: int64
          description: ウイルス対策ステータスID(ディクショナリ項目に関連：ANTIVIRUS_STATUS)
        no_symantec_reason:
          type: string
          description: Symantec未導入理由
        remark:
          type: string
          description: 備考
        create_time:
          type: string
          format: date-time
          description: 作成時間
        update_time:
          type: string
          format: date-time
          description: 更新時間
        updater:
          type: string
          description: 更新者
        is_deleted:
          type: integer
          format: int16
          description: 論理削除フラグ(0=未削除、1=削除済)
      required:
        - permission_id
        - job_number

    
security:
  - BearerAuth: []
