openapi: '3.0.3'
info:
  title: 辞書管理　API
  version: '1.0'

paths:
  /dict/items:
    get:
      summary: 辞書項目の取得
      description: 登録されている辞書項目を取得します（sortフィールドで昇順ソート済）。
      tags:
        - Dict
      security:
        - bearerAuth: []
      parameters:
        - name: dictTypeCode
          in: query
          required: true
          schema:
            type: string
          description: 辞書タイプコードでフィルタリング
          example: "USB_STATUS"
      responses:
        '200':
          description: 辞書項目の取得に成功しました
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictItemsResponse'
              examples:
                successExample:
                  $ref: '#/components/examples/DictSuccessExample'
        '400':
          description: パラメータ不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictItemsResponse'
              examples:
                paramErrorExample:
                  $ref: '#/components/examples/DictParamErrorExample'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DictItemsResponse'
              examples:
                serverErrorExample:
                  $ref: '#/components/examples/DictServerErrorExample'

components:

  examples:
    DictSuccessExample:
      summary: 取得成功例
      value:
        code: 200
        message: "成功"
        data:
          - dictId: 1
            dictItemName: "使用可"
            sort: 1
          - dictId: 2
            dictItemName: "使用不可"
            sort: 2

    DictParamErrorExample:
      summary: パラメータ不正例
      value: { code: 40001, message: "dictTypeCodeは文字列で指定してください", data: null }

    DictServerErrorExample:
      summary: サーバー内部エラー例
      value: { code: 50000, message: "システムエラーが発生しました", data: null }

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorization: Bearer <token>"

  schemas:
    DictItemsResponse:
      type: object
      properties:
        code:
          type: integer
          description: 処理結果コード
          example: 200
        message:
          type: string
          description: 処理メッセージ
          example: "成功"
        data:
          type: array
          nullable: true
          description: 辞書データ、sort フィールドで昇順ソート済、dictId=value、dictItemName=label
          items:
            $ref: '#/components/schemas/DictItem'

    DictItem:
      type: object
      description: 統合辞書テーブルのデータ（下拉框用：dictId=value、dictItemName=label）
      properties:
        dictId:
          type: integer
          format: int64
          description: 辞書ID（下拉框value値）
          example: 1
        dictItemName:
          type: string
          description: 辞書項目名（下拉框label値）
          example: "使用可"
        sort:
          type: integer
          description: ソート番号（昇順でソート済）
          example: 1