openapi: 3.0.0
info:
  title: 用户管理系统 API
  description: 一个示例用户管理系统的OpenAPI规范
  version: 1.0.0
  contact:
    name: API 支持
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: 生产服务器
  - url: https://staging-api.example.com/v1
    description: 测试服务器

tags:
  - name: 用户
    description: 用户管理操作
  - name: 认证
    description: 用户认证相关操作

paths:
  # 认证相关端点
  /auth/login:
    post:
      tags:
        - 认证
      summary: 用户登录
      description: 使用用户名密码获取访问令牌
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: 认证失败
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  # 用户相关端点
  /users:
    get:
      tags:
        - 用户
      summary: 获取用户列表
      description: 获取系统中的所有用户（支持分页和过滤）
      operationId: getUsers
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: limit
          in: query
          description: 每页数量
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
            minimum: 1
        - name: role
          in: query
          description: 按角色过滤
          required: false
          schema:
            type: string
            enum: [admin, user, guest]
      responses:
        "200":
          description: 用户列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
                  pagination:
                    $ref: "#/components/schemas/Pagination"

    post:
      tags:
        - 用户
      summary: 创建新用户
      description: 创建一个新用户账户
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: 用户创建成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: 无效的请求数据

  /users/{userId}:
    get:
      tags:
        - 用户
      summary: 获取指定用户信息
      description: 根据用户ID获取详细信息
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          description: 用户ID
          schema:
            type: string
            pattern: "^[a-f0-9]{24}$"
      responses:
        "200":
          description: 用户信息
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: 用户不存在

    put:
      tags:
        - 用户
      summary: 更新用户信息
      description: 更新指定用户的信息
      operationId: updateUser
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "200":
          description: 更新成功
        "403":
          description: 权限不足

    delete:
      tags:
        - 用户
      summary: 删除用户
      description: 删除指定用户
      operationId: deleteUser
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: 删除成功
        "404":
          description: 用户不存在

  /users/{userId}/avatar:
    post:
      tags:
        - 用户
      summary: 上传用户头像
      description: 上传用户头像图片
      operationId: uploadAvatar
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                  description: 头像图片文件
      responses:
        "200":
          description: 上传成功

components:
  schemas:
    # 请求模型
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: john.doe
        password:
          type: string
          format: password
          example: mysecretpassword

    CreateUserRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
          example: john.doe
        email:
          type: string
          format: email
          example: john@example.com
        password:
          type: string
          format: password
          minLength: 6
          example: securepass123
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        role:
          type: string
          enum: [admin, user, guest]
          default: user

    UpdateUserRequest:
      type: object
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: john.new@example.com

    # 响应模型
    User:
      type: object
      properties:
        id:
          type: string
          example: 507f1f77bcf86cd799439011
        username:
          type: string
          example: john.doe
        email:
          type: string
          format: email
          example: john@example.com
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        role:
          type: string
          example: user
        createdAt:
          type: string
          format: date-time
          example: 2024-01-15T10:30:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2024-01-20T14:45:00Z

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        tokenType:
          type: string
          example: Bearer
        expiresIn:
          type: integer
          example: 3600
        user:
          $ref: "#/components/schemas/User"

    Pagination:
      type: object
      properties:
        total:
          type: integer
          example: 100
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 20
        totalPages:
          type: integer
          example: 5

    Error:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: 用户不存在
        timestamp:
          type: string
          format: date-time
          example: 2024-01-20T10:30:00Z

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 使用JWT令牌进行认证

  parameters:
    PageParam:
      name: page
      in: query
      description: 页码
      required: false
      schema:
        type: integer
        default: 1
        minimum: 1

    LimitParam:
      name: limit
      in: query
      description: 每页数量
      required: false
      schema:
        type: integer
        default: 20
        maximum: 100
        minimum: 1

  responses:
    UnauthorizedError:
      description: 认证失败或令牌无效
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 401
            message: 无效的访问令牌
            timestamp: "2024-01-20T10:30:00Z"

    NotFoundError:
      description: 请求的资源不存在
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 404
            message: 资源不存在
            timestamp: "2024-01-20T10:30:00Z"
